import type { Metadata } from "next";
import "./globals.css";
import Header from './components/header/header.jsx';
import Footer from './components/footer/footer.jsx';
import Sidebar from "./components/sidebar/sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex gap-60 body" >
      
         <div >

            <Sidebar />
         </div>

          <div className="flex flex-col w-screen " >
            
            <Header />

            {children}

            <Footer />

          </div>

       


      </body>
    </html>
  );
}
